# Generated by Django 4.2.4 on 2023-10-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagementTool', '0002_notes_errors_bugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
